### ISSUE TITLE
List en row view in het View menu

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#101]
Hee Martijn,

Is het mogelijk om List en Row op andere plekken in de lijst te zetten? Voor mij is de volgorde nu niet helemaal logisch. 
Je ziet nu eerst de verschillende material types, met daaronder een grijze lijn (nog logisch voor mij)
Ik zou 

famine
location
person
tiles
rows
keyword
map

veranderen naar

famine
location
person
keyword
----grijze streep----
tiles
rows
maps
----grijze streep---- (die staat er al)

Dan staan alle view manieren bij elkaar gegroepeerd.

Lindsay

**Comment by martijnbentum** [comment]
gedaan
