### ISSUE TITLE
Add person --> protocoltekst bij vlaggetje 

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#103]
Hee Martijn,

Ik kan volgens mij de protocolteksten bij het vlagsymbool niet aanpassen. Kun jij daar bij Add Person toevoegen: "Use the flag symbol to indicate an important person. This person will be shown more prominently in search results."

Alvast bedankt!

Lindsay

**Comment by martijnbentum** [comment]
De tekst voor het vlaggetje kan je met 'Flag symbol' aanpassen/toevoegen.
<img width="823" alt="Screen Shot 2021-07-09 at 16 28 40" src="https://user-images.githubusercontent.com/19554953/125093890-13369e80-e0d3-11eb-9713-bbb6e89288e1.png">

**Comment by LindsayJanssen** [comment]
Wow, dat ik daar eerder overheen gekeken heb...tijd voor vakantie.
