### ISSUE TITLE
Add music --> protocol thumbnail

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#104]
Hee Martijn,

Bij Add music heeft de thumbnail nog geen protocoltekst. Ik heb deze zelf geprobeerd toe te voegen middels het lege veld onderaan de protocolteksten, maar mijn toevoeging wordt niet opgeslagen. Kun jij de volgende tekst toevoegen?:

Upload a thumbnail image here of max. 400x400 pixels (or about 300kb); this will be displayed alongside the entry in the repository. After uploading your image, look at it, to see whether it is of sufficient quality. Add "_thumb" to your file name, so for example: "dali_thepersistenceofmemory_thumb.jpg". Only use images for which you have use permission.

Bedankt!

L.

**Comment by martijnbentum** [comment]
Kan jij even testen of het nu voor je werkt zie issue 106

**Comment by LindsayJanssen** [comment]
Het werkt! Ik kan tekst toevoegen.

L.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
