### ISSUE TITLE
Welke locatie wordt gebruikt voor memorial sites op de kaart?

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#105]
Hee Martijn,

Een vraag: welke locatie wordt gebruikt om memorial sites op de kaart weer te geven? Is dat Setting of Locations? Mijns inziens is de laatste het meest logisch (om de daadwerkelijke locatie van  een monument zichtbaar te maken).

Hartelijke groet!

Lindsay

**Comment by martijnbentum** [comment]
Memorial sites waren nog niet zichtbaar. Ik heb het toegevoegd. Locations wordt gebruikt voor de positie op de kaart
