### ISSUE TITLE
Add person --> toevoegen protocoltekst thumbnail

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#106]
Hee Martijn,

Bij Add person staat er nog geen protocoltekst bij the thumbnailveld; ik kan deze zelf niet toevoegen. Kun jij dat tekstje aanmaken? Dit kun je kopiëren:

Upload a thumbnail image here of max. 400x400 pixels (or about 300kb); this will be displayed alongside the entry in the repository. After uploading your image, look at it, to see whether it is of sufficient quality. Add "_thumb" to your file name, so for example: "dali_thepersistenceofmemory_thumb.jpg". Only use images for which you have use permission.

Bedankt!

L.

**Comment by martijnbentum** [comment]
Hoi Lindsay,

Er was een bug bij het toevoegen van een nieuw veld. Het werkt nu weer, dus nu kan je zelf ook protocoltekst voor een nieuw veld toevoegen.

Groet,
Martijn
<img width="805" alt="Screen Shot 2021-07-09 at 15 50 13" src="https://user-images.githubusercontent.com/19554953/125088305-948b3280-e0cd-11eb-8953-41db8aa8474a.png">
