### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#108]
**verfijnen zoekopdrachten:**

- types of material, met verdere specificatie naar subtypes (dus niet alleen tekst, maar ook verder kunnen specificeren naar novels, poems, articles, etc.).
- location(s)
- famine(s)
- keywords: sowieso de overkoepelende categorie-woorden
- language
- material type
- tijdsindicatie: met slider of het invoeren van begin- en einddata of decennia

**ordenen**:
- On time/period: newest to oldest and vice versa
- On famine(s)
- On material type
- On location (country level; more specific insight can be obtained via map view)
- Additional filter on age group (14 and under, over 14 and OK for all ages).

Hee Martijn,

Ik zet even het punt over hierarchy in search results dat we gisteren besproken hebben, hier als issue. Als de gebruiker een search query heeft gedaan, zou het mooi zijn als hij/zij daarna de mogelijkheid heeft de zoekresultaten te ordenen. Dit zijn die opties die we graag zouden zien (excuses voor het code switchen):

- On time/period: newest to oldest and vice versa
- On famine(s)
- On material type
- On location (country level; more specific insight can be obtained via map view)

- Additional filter on age group (14 and under, over 14 and OK for all ages).

We vinden de Delpher (KB) interface een mooi voorbeeld hier (en verwachten niet dat je even kan nadoen wat een heel team aan developers heeft gemaakt!;-))

Hartelijke groet,

L.

Hee Martijn,

N.a.v. onze bespreking is dit het lijstje geworden voor het verder verfijnen van zoekopdrachten:

tijdsindicatie: met slider of het invoeren van begin- en einddata
types of material, met verdere specificatie naar subtypes (dus niet alleen tekst, maar ook verder kunnen specificeren naar novels, poems, articles, etc.).
location(s)
famine(s)
keywords: sowieso de overkoepelende categorie-woorden; indien haalbaar ook alle keywords.
De meer specifieke elementen hierboven (subtypes en alle keywords) zijn misschien afhankelijk van de vraag die je (terecht) stelde: hoeveel moeite hierin te steken, niet wetende of de beoogde eindgebruiker ook daadwerkelijk gebruik maakt (en kan blijven maken) van de repository, dus ik kan me voorstellen dat je even wacht met dat finetunen totdat er meer duidelijkheid is over het toekomstig gebruik van de repository.

Bedankt en hartelijk groet!

L.

**Comment by martijnbentum** [comment]
Hee Martijn,

N.a.v. onze bespreking is dit het lijstje geworden voor het verder verfijnen van zoekopdrachten:

tijdsindicatie: met slider of het invoeren van begin- en einddata
types of material, met verdere specificatie naar subtypes (dus niet alleen tekst, maar ook verder kunnen specificeren naar novels, poems, articles, etc.).
location(s)
famine(s)
keywords: sowieso de overkoepelende categorie-woorden; indien haalbaar ook alle keywords.
De meer specifieke elementen hierboven (subtypes en alle keywords) zijn misschien afhankelijk van de vraag die je (terecht) stelde: hoeveel moeite hierin te steken, niet wetende of de beoogde eindgebruiker ook daadwerkelijk gebruik maakt (en kan blijven maken) van de repository, dus ik kan me voorstellen dat je even wacht met dat finetunen totdat er meer duidelijkheid is over het toekomstig gebruik van de repository.

Bedankt en hartelijk groet!

L.

**Comment by LindsayJanssen** [comment]
Hee Martijn,

Bedankt voor het doorsturen hiervan! Was dat alleen ter verificatie dat ik het inderdaad eerder aan je had gecommuniceerd, of wil je dat ik hier nu nog iets mee doe?:-)

Hartelijke groet,

Lindsay

**Comment by martijnbentum** [comment]
The first setup of search with filtering is complete, refinements are specified in new issues
