### ISSUE TITLE
make sidebar filter main categories collapsible

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/heritages#116]
add button to fold up filters under a specific filter category

**Comment by martijnbentum** [comment]
filter categories can now be collapsed

**Comment by LindsayJanssen** [comment]
Ik zie het; handig! Ik zou wel een klein icoontje (klein neerwaarts/opwaarts pijltje o.i.d.) toevoegen om aan te geven dat de filter categorie collapsible is. Ik denk niet dat gebruikers anders doorhebben dat ze op de titel van de categorie kunnen klikken om die in of uit te vouwen.
