### ISSUE TITLE
Secondary layer view person broken image

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#124]
Hee Martijn,

Wanneer ik op een persoon klik die voorzien is van een afbeelding in tile view, krijg ik een broken image icoon te zien in het popup scherm, ook voor personen waarvoor wel een thumbnail geüpload is. Zie het voorbeeld van A. den Doolaard:

![image](https://user-images.githubusercontent.com/69973344/157398206-a2db4a04-9533-420e-96b3-533a9111bc29.png)

Komt dit omdat er naast de thumbnail niet ook nog een volledige image geüpload is? Zo ja, dan moet ik in het protocol aangeven dat men altijd zowel een thumbnail als een full image uploadt.

Hartelijke groet,

Lindsay

**Comment by martijnbentum** [comment]
Ja, maar bij person is er geen mogelijkheid om een volledige image te uploaden. Ik zal het aanpassen dat als er geen volledige afbeelding is dat de thumbnail gebruikt wordt. Lijkt me wel goed om aan te moedigen om waar mogelijk ook volledige afbeeldingen te uploaden.

**Comment by martijnbentum** [comment]
fixed
