### ISSUE TITLE
In list view worden sommige titels gecentreerd

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#125]
Hoi Martijn,

Excuses voor het muggenziften dat volgt. In list view worden de titels van sommige afbeeldingen gecentreerd, terwijl het gros van de titels links uitgelijnd staat. Kun je dit rechttrekken?

Bedankt!

**Comment by martijnbentum** [comment]
ok

**Comment by martijnbentum** [comment]
titels zijn nu altijd links uitgelijnd
