### ISSUE TITLE
Speciale tekens in tekstveld 

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#126]
Hee Martijn,

Tijdens onze vorige vergadering hadden we het gehad over het vermijden van speciale tekens in titelvelden, omdat die niet goed overgenomen worden. Dit probleem doet zich ook voor bij (sommige) tekstbestanden. Kijk bijvoorbeeld maar naar de entry 'An Elegy' (1740). Daar heeft Eliza het gedicht geüpload als een .rtf bestand, waarin de speciale tekens zichtbaar zijn. Wanneer je de entry in de repository ziet, zijn de speciale tekens echter veranderd in blokjes. Heeft dit mogelijk wat te maken met het .rtf format? Zo ja, dan vervang ik het met een .txt of PDF bestand.

Zo nee, hoe kunnen we dit het beste oplossen? Aangeven in de beschrijving dat het downloaden van de file de correcte weergave geeft, of de weergave in het browser venster uitschakelen en de  eindgebruiker alleen het tekstbestand laten downloaden? Of het zo laten? Of ....?

Aanvulling, bij deze items zie ik hetzelfde probleem:
Famine - A Poem (1742; ook .rtf)
George Berkeley to George Faulkner, 17 February 1741 (1741; ook .rtf)
Jonathan Swift to Mrs. Whiteway, 3 February 1739-40 (.rtf)

**Comment by LindsayJanssen** [comment]
Hee Martijn,

Ik had al in het protocol staan dat men alleen .txt of .pdf mag gebruiken. Blijkbaar lezen literatuurwetenschappers niet goed de fine print;-) Zal ik die files van Eliza zelf even converteren en opnieuw uploaden als .txt of .pdf?

**Comment by martijnbentum** [comment]
;-) ja is goed
