### ISSUE TITLE
Generic images voor de repository

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#127]
Hoi Martijn,

Ik ben op zoek naar vrij te gebruiken algemene afbeeldingen (dus boeken/teksten voor 'text'; mensvormen voor 'person', etc.) voor repository items waarvoor we geen specifieke afbeeldingen hebben. Ik meen me te herinneren dat je het geen goed idee vond om daar gewoon de icons voor te gebruiken die we al hebben (die van fontawesome), maar weet niet meer waarom dat het geval is...of heb ik dat verkeerd onthouden, en zie je geen probleem met het gebruiken van (grotere versies van) de bestaande icons?

L.

**Comment by martijnbentum** [comment]
Hoi Lindsay,

Ik weet ook niet meer waarom ik het geen goed idee vond ;-). Misschien omdat het lastiger implementeren is. Je kan namelijk een default afbeelding opgeven voor als er geen afbeelding beschikbaar is. De iconen zijn geen afbeelding. Ik moet daar dan een oplossing voor vinden.

Dus mijn voorkeur zou zijn afbeeldingen, maar ik kan kijken of ik een oplossing kan vinden voor de icoon optie.

Groet,
Martijn

**Comment by martijnbentum** [comment]
will try to use icons as generic images see #130
