### ISSUE TITLE
MUST HAVE: Verfijnen van zoekresultaten op tijdsperiodes

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#137]
De datumspecificatie zou in kortere periodes verdeeld moeten worden.
Voor de 20e en 21e eeuw: per decennia
Voor 1845-1900: blokken van 20 a 25 jaar
Daarvoor: per 50 jaar

Als het menu aan de linkerzijde hierdoor te vol wordt, kun je ook overwegen deze date specification als fold out menu te geven.

Als alternatief kan ook gekozen worden voor het werken met een tijdslijn met schuifjes.

**Comment by martijnbentum** [comment]
Ik heb een tijdslijn met schuifjes toegevoegd

**Comment by LindsayJanssen** [comment]
Heel fijn! Goed dat de eindgebruiker zo heel precies de periode kan afbakenen.
