### ISSUE TITLE
MUST HAVE: extra veld bij monumenten -- link naar original website

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#138]
Voor een aantal monumenten maken we gebruik van de foto's van websites van anderen. We verwijzen dan nu in de beschrijving naar de website, maar dat is niet nodig als we een veld hebben voor die link (wellicht met een naam als "link to original website" o.i.d.).

**Comment by martijnbentum** [comment]
Ik heb het veld source link toegevoegd. Zo heet het veld bij andere categorieën ook.

**Comment by LindsayJanssen** [comment]
Prima! Wel het volgende: ik heb een source link toegevoegd bij Faoin Sceach (abstract monument van een boom), maar zag daar niet dat de source link dan ook zichtbaar wordt in end user view? Ook na pagina vernieuwen of opnieuw inloggen niet.

**Comment by martijnbentum** [comment]
Ik zie geen source link bij faoin sceach (memorial site). De source link zouden nu wel zichtbaar moeten worden bij de detail view
