### ISSUE TITLE
MUST HAVE: download button -> download optie moet worden uitgeschakeld

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#139]
De mogelijkheid voor de eindgebruiker om materiaal waarbij dat mag, te downloaden.

**Comment by martijnbentum** [comment]
It should be possible to easily download image and text files if this is allowed

-> How should it be determined if a file can be downloaded?
Currently there is no copyright field for items, also use permission is currently used for displaying on the website not explicitly for downloading.

**Comment by LindsayJanssen** [comment]
Use permission lijkt me inderdaad. Wellicht een stomme vraag: maar welke metadata bedoel je precies?

**Comment by martijnbentum** [comment]
Met metadata bedoel ik de data die jullie hebben ingevoerd.

Het is nu mogelijk om de afbeeldingen te downloaden door erop te klikken

**Comment by martijnbentum** [comment]
Een extra optie is nodig bij use permission 'download' om het verschil te maken tussen tonen en downloaden. Moet nog besloten worden of deze optie wordt toegevoegd. Anders geen download optie.

**Comment by LindsayJanssen** [comment]
We hebben dit punt op 11 oktober 2022 besproken, en besloten toch geen downloadfunctie te willen aanbieden; excuses voor het onnodige werk! (Afweging tussen uitzoeken van rechten voor elk item of niet.)

**Comment by martijnbentum** [comment]
download optie uitgeschakeld
