### ISSUE TITLE
Kleine aanpassing tekst op homepage

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#147]
Hee Martijn, zou je de eerste 2 alinea's op de homepage kunnen aanpassen? Dit is die nieuwe tekst:

This repository is an open-access educational resource which contains primary materials related to historical periods of hunger in Europe. The memories of these periods continue to impact debates on new crises and conflicts, such as economic decline, refugees, Brexit, COVID-19, and war. Often, memories of past hunger are evoked to stress conflict and difference. The materials collected here serve to demonstrate that such memories actually offer possibilities for transnational understanding of contested histories. The repository is set up from this transnational angle and through it, we seek to make explicit links between different periods of hunger. You are encouraged to use the materials in this repository in your teaching and learning.

It is our hope that this repository will help you to engage with these materials in comparative but not competitive ways, and that it will stimulate empathy and understanding across borders.

**Comment by martijnbentum** [comment]
gedaan
