### ISSUE TITLE
clear & change image not working at the same time

### ISSUE THREAD

**Issue by CharleyBoerman** [martijnbentum/heritages#156]
When an entry already has an image (either for images or for thumbnail), you have to first delete the image and save the entry, before you can upload and save the new image. Would it be possible to do this in one go?

**Comment by martijnbentum** [comment]
Hoi Charley,
Ik heb het met Image geprobeerd en daar kan ik het in 1 keer vervangen. Je moet dan niet het clear vakje aan vinken. Werkt het bij jou dan ook of ging het bij een andere categorie mis?
Groet,
Martijn

**Comment by CharleyBoerman** [comment]
Hi Martijn,

Ah ja, zo werkt het voor mij ook! Bedankt :)

Groet,
Charley

Op 14 nov. 2022, om 09:00 heeft martijnbentum ***@***.***> het volgende geschreven:



Hoi Charley,
Ik heb het met Image geprobeerd en daar kan ik het in 1 keer vervangen. Je moet dan niet het clear vakje aan vinken. Werkt het bij jou dan ook of ging het bij een andere categorie mis?
Groet,
Martijn
