### ISSUE TITLE
comma's between donor lists

### ISSUE THREAD

**Issue by CharleyBoerman** [martijnbentum/heritages#158]
could we automatically add comma's when multiple donors/institutions are involved, so that it is clear for the viewer that these are different institutions? (see screenshot)

![Scherm­afbeelding 2022-11-09 om 10 34 04](https://user-images.githubusercontent.com/70149523/200793957-bd798f0c-ab54-4ae6-96d9-703bc0c9f460.png)

**Comment by martijnbentum** [comment]
commas between different institutions should be visible now
