### ISSUE TITLE
Clear settings does not (always) work

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#161]
When you narrow down your search results with the categories in the left-side bar, it isn't always possible to clear these categories and get back to your full list. Somehow, the repository remembers the selection, and clicking on selected terms to deselect them doesn't always work. Last time, I could only clear these settings by logging out and in of the repository.

**Comment by martijnbentum** [comment]
Added a 'clear all' button to clear all filters and the search query
