### ISSUE TITLE
Getting past the login screen.(Which seems like the most basic problem ever.)

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#2]
Hi Martijn,

I created an account and logged into the website. When I log in, this is what I see:
![image](https://user-images.githubusercontent.com/69973344/90776533-7fad8100-e2fa-11ea-9706-cd5ef5b257f1.png)
When I then try to add materials and select a type of material from the 'Add' menu, I am simply taken back to the screen I shared above (with my name included above 'Login'). I've tried to do this via Chrome and via Firefox; the result was unfortunately the same. Do you know how to solve this problem?

Thanks and best,

Lindsay

**Comment by CharleyBoerman** [comment]
Hi Martijn,

I appear to have the same issue as Lindsay! 

Thanks and best,

Charley

**Comment by martijnbentum** [comment]
Hi Lindsay,

Yes, but this is intended. Only users with permission can enter the website.
I added you to the data_entry group, so you can now enter the website and enter data. 

I also added you to the staff, which allows you to change user privileges on the admin page:
https://heritagesofhunger.cls.ru.nl:4432/admin/

<img width="640" alt="Screen Shot 2020-08-20 at 16 06 56" src="https://user-images.githubusercontent.com/19554953/91272657-59fdfd00-e77c-11ea-9ebe-2742b40cb4e7.png">

If you click on Users

<img width="640" alt="Screen Shot 2020-08-20 at 16 07 48" src="https://user-images.githubusercontent.com/19554953/91272693-671aec00-e77c-11ea-87ef-5944b9bbb38c.png">

You see a list of Users. By clicking on the username you can change the settings for that user. If someone should be able to access the admin page you can check the ‘Staff status’ box. If someone should only be able to enter data you can add the data_entry group to the user.

<img width="550" alt="Screen Shot 2020-08-20 at 16 09 54" src="https://user-images.githubusercontent.com/19554953/91272706-6d10cd00-e77c-11ea-9749-b1d0911c102b.png">


If anything is unclear or not working please let me know.

Best,
Martijn

**Comment by martijnbentum** [comment]
Hi Charley,

You should be able to enter the site now. See also:https://github.com/martijnbentum/heritages/issues/2 <https://github.com/martijnbentum/heritages/issues/2>

Best,
Martijn

**Comment by gloriaroman** [comment]
Hi Martijn,

I have the same 'problem' as Lindsay and Charley. Could you, please, give me permission to enter the website and to enter data?

Thank you.

Best,

Gloria

**Comment by martijnbentum** [comment]
Hi Gloria,

You should be able to enter the site now.

Best,
Martijn
