### ISSUE TITLE
create item views

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/heritages#20]
Show the information of an individual item (e.g. a film).
If you have any preferences about which fields to include for the different objects (e.g. film, text, etc), let me know.

**Comment by LindsayJanssen** [comment]
Do you mean what the end user will immediately see when they consult the repository? This would be a good discussion point for our meeting! Will list it for discussion!

**Comment by martijnbentum** [comment]
item view (aka detail view) are implemented
