### ISSUE TITLE
double entries / uniqueness constraints

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/heritages#28]
For each model a combination of fields is specified that makes an entry unique.
This should be a _minimal_ combination of fields that allows entries that resemble each other to still be entered. Fields that can contain multiple values cannot be used for uniqueness constraints (e.g. for **film** the 'writers' field cannot be used).

For example, for **person** only using the field 'name' might not be enough because there are people that share a name. 'Name' + 'date of birth' could be enough, since it is unlikely that there will be multiple persons in the database with the same name and birthday. It is best to only use this minimal combination, otherwise double entries might not be detected.

film
----
* title original
* date released

image
----
* title original
* image file

infographic
----
* title original
* image file

music
----
* title original
* date released

picture story
----
* title original
* image file

text
----
* title original
* date published

famine
----
* no constraints

location
----
* name
* latitude
* longitude

person
----
* name
* date of birth

**Comment by martijnbentum** [comment]
I implemented all constraints

**Comment by LindsayJanssen** [comment]
Seems to be working well! Thanks!
