### ISSUE TITLE
Points discussed during HoH - HL meeting 28 Aug.2020

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#3]
Hoi Martijn! Ik heb zoveel mogelijk de punten eruit gelaten die op inhoud sloegen. De lijst is nu:

All materials
•	There is not yet an option to include rating (<14, >14, all ages)
•	…. Include date(s)?
•	I would first put "title original" and then "title English". "Title English" cannot be left empty? We discussed to put “original first”, then that becomes the default and “English” can be left empty.
•	Uploading files doesn’t (always) work.

Add Film
•	Locations shot: if I want to add a country, it shows the “|” behind the name (“Ukraine |”). How can we avoid this? I don’t want to add specific cities, because this information is not always available plus it will be a lot of work.
•	Location released: same as above. 
•	Year released: Do we want to add info on the release year? I think that’s very important with film.
•	Target audience: for "both" I would say "(both) national and international”. When viewed by itself, “both” makes little sense.

Add Person
•	Occupation: I can only add one occupation, but some are actor, writer and producer. How can I add more occupations?
•	No possibility to enter dates of birth and death?
 
Location
•	You cannot select locations in the US (outside of Europe)?
 
Text:
•	Date of publication and of creation are missing
•	Publishing outlet is missing
•	What do we do when an author is an institution, group, etc?
 
Infographics:
•	"Date" is missing
 
 Music:
•	Release date is missing
•	Should we have the option to mention an album (we didn’t have this as an option in the Excel either).
  
Location:
•	If a location is not yet available, do we add one ourselves? And how does that work?

Image:
•	No publishing outlet?
•	No way to enter date of publication?
 
Hartelijke groet!

Lindsay

**Comment by martijnbentum** [comment]
Thanks for the issues. It would be nice if issues are entered separately with a descriptive title and appropriate label. This allows me to refer to the issues in the updates of the code and makes everything a bit more organised.

**Comment by martijnbentum** [comment]
moved to separate issues
