### ISSUE TITLE
toevoeging: person image

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#32]
Hoi Martijn!
Kun je voor 'Person' de mogelijkheid om een afbeelding van de persoon te uploaden, toevoegen?
Hartelijk dank!

**Comment by martijnbentum** [comment]
gedaan

**Comment by LindsayJanssen** [comment]
Hee Martijn, kan het zijn dat ik dat veld nog niet zie? Ik zie bij 'Add person' voor het toevoegen van image files alleen de optie om een thumbnail te uploaden, niet een image.

**Comment by martijnbentum** [comment]
Ik denk dat ik het thumbnail veld had toegevoegd voor de afbeelding.
Wil je ook nog een apart veld voor een afbeelding?

**Comment by LindsayJanssen** [comment]
Ja, doe maar. Bedankt!
