### ISSUE TITLE
Location loading /saving issue

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/heritages#37]
Some location would not show in the autocomplete field
e.g. could not find the location Spain

**Comment by martijnbentum** [comment]
The location Spain was in the database, however the server had problems loading locations with the autocompletion field (e.g. used in the add film form)

I changed the autocomplete to only start loading location names after typing two characters
Also it only searches locations that start with the same characters that are typed.

There are different messages you can get when using the autocomplete field

no results found -> this means there is no location matching that name
could not load the results -> this means the server could not complete the request, the locations could be in the database
(it is possible to search the database: under view go to location and search for the location you want to add)
It could be useful to add this to the protocol to prevent duplicate additions to the database

The changes I made should prevent the could not load the results message most of the times, but it can still occur if the server gets a lot of requests. Let me know if there are still problems.

**Comment by LindsayJanssen** [comment]
Dit issue zit deels in het andere locatie issue, en je suggestie is toegevoegd aan de protocollen, dus ik sluit dit issue!
