### ISSUE TITLE
add person leads to 'key error'

### ISSUE THREAD

**Issue by CharleyBoerman** [martijnbentum/heritages#38]
I want to add a person (Igort, comic artist), but when I want to save the contribution the site gives me a 'key error' and a list of code (see screenshot). I tried to add the person again without including an image, but this led to the same result. 

![Schermafbeelding 2021-01-07 om 14 45 56](https://user-images.githubusercontent.com/70149523/103899704-11295e00-50f7-11eb-8a51-602377f2d8e3.png)

**Comment by martijnbentum** [comment]
It should work again
