### ISSUE TITLE
add picture story leads to value error

### ISSUE THREAD

**Issue by CharleyBoerman** [martijnbentum/heritages#39]
I tried to add a picture story, and it gave me a long error list.

Underneath it says: "You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code."

<img width="1440" alt="Schermafbeelding 2021-01-13 om 09 25 49" src="https://user-images.githubusercontent.com/70149523/104425748-54fde680-5581-11eb-99ce-12abc389f9f1.png">

**Comment by martijnbentum** [comment]
Could you let me know what you tried to enter in the date field?

**Comment by CharleyBoerman** [comment]
Ah you're right, I wanted to indicate a range, but listed 2010-2016, but should have done 2016. Sorry about that, still learning how to work with the protocols!

**Comment by martijnbentum** [comment]
No problem. I still need to implement a better feedback system. You can also find the protocol if you hover over the field names
