### ISSUE TITLE
permission for thumbnail person?

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#40]
Hee Martijn,

Dit geldt voor thumbnails by 'add person': voor de meeste thumbnails zullen we use permission hebben, maar wellicht is het goed om een permission veld toe te voegen voor de afbeeldingen waar we dat nog niet voor hebben.

Alvast bedankt! Hartelijke groet,

Lindsay

**Comment by martijnbentum** [comment]
Hoi Lindsay,

Ik kan het zeker toevoegen, maar misschien is het een idee om voor deze afbeeldingen alleen afbeeldingen met use permission te gebruiken? Als de thumbnail niet getoond mag worden heeft die toch maar weinig nut?

Groet,
Martijn

**Comment by LindsayJanssen** [comment]
Goed punt! Zou je dit dan kunnen plaatsen als protocoltekst voor de thumbnail onder add person?:

Upload a thumbnail of the image of the person here of max. 400X400 pixels (or about 300kb); this will be displayed alongside the entry in the repository. Only upload an image here if you have use permission for that image; if this is not the case, do not upload anything.

**Comment by martijnbentum** [comment]
gedaan
