### ISSUE TITLE
(zelfde issue) met 'add locations'

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#41]
Hee Martijn,

Een aantal plaatsnamen worden nog steeds niet gevonden in de locations database. Gloria en ik hadden beiden het probleem, bijvoorbeeld bij de volgende plaatsnamen:
- Gomshall (Surrey, England)
- Surrey (England)
- England (hoe wordt dat niet gevonden?!)
- Hazelhatch (Co. Kildare, Ireland)
-  ‘Galicia’ (Spanje)
- ‘Basque Country’ 
- Ardfert (Co. Kerry, Ireland)
-  Co. Kerry
Voor deze plaatsen, geeft het veld: "no locations found)" 
- Munster wordt op verschillende locaties gevonden, maar daar zit Munster in Ierland niet bij.
- Hetzelfde geldt voor Somerset (UK)
 
Als we zelf proberen die plaatsen toe te voegen, krijgen we geen foutmelding, maar toch is de toegevoegde plaats dan geen onderdeel geworden van de database.

Alvast bedankt! Hartelijke groet,

Lindsay

**Comment by martijnbentum** [comment]
Ik ga het bekijken.

**Comment by martijnbentum** [comment]
Ik heb een paar dingen bekeken.

-Galicia was aan de database toegevoegd zonder location type. Hierdoor ontstond een error als hierop gezocht werd. Ik zal location type verplicht maken in het form.

-In het add location form heb ik het location containing veld aangepast zodat alleen die locaties teruggeeft waarmee de eerste letters corresponderen (dit voorkomt een overload aan resultaten)

-Ik kan Munster toevoegen en daarna ook vinden in de database

-United Kingdom staat als land in de database. 
Je kan England wel bij regio zien staan, maar die is niet zelf als entry in de database geladen.  In de database is England een regio binnen de United Kingdom. Ik heb de regio's niet allemaal als aparte entries ingeladen (die informatie staat vermeld bij de stad), om de database een beetje te ontzien. Het is mogelijk om zelf England toe te voegen.

-Werkt het nu beter?

**Comment by martijnbentum** [comment]
Ik heb alle locaties zonder locatie type verwijderd. 

Ik heb ook nog even alle locaties bekeken die niet gevonden werden.

Gomshall (Surrey, England)
Surrey (England)
England (hoe wordt dat niet gevonden?!)
Hazelhatch (Co. Kildare, Ireland)
‘Galicia’ (Spanje)
‘Basque Country’
Ardfert (Co. Kerry, Ireland)
Co. Kerry
Voor deze plaatsen, geeft het veld: "no locations found)"
Munster wordt op verschillende locaties gevonden, maar daar zit Munster in Ierland niet bij.
Hetzelfde geldt voor Somerset (UK)

Voor deze locaties geldt dat ze niet in de database zitten, maar wel toegevoegd kunnen worden. Munster in Ireland heb ik nu toegevoegd.

Ter informatie. Ik zag in de database een locatie entry met als naam Connemara, Ireland. Het is beter om Connemara in te voeren en dan Ireland in te voeren bij het 'containing location' veld onderaan.

**Comment by LindsayJanssen** [comment]
Hoi Martijn,

Ik vermoed dat dat Connemara, Ireland, een overblijfsel is van een vroege probeersessie met de database; hopelijk zorgt de huidige vorm van de add location optie ervoor dat de groepsleden het automatisch correct invullen. Maar je hebt gelijk, het is wel goed hier alert op te zijn.

Goed om te weten dat die location fouten ook regelmatig het gevolg zijn van het feit dat wij vergeten het location type (goed) aan te geven – en dat je dat nu een verplicht veld hebt gemaakt!

Het VK als land is logisch; maar technisch gezien is Engeland een land binnen het VK – ik ben benieuwd wat de Engelsen ervan vinden gedegradeerd te zijn tot region😉

Ik kan helaas nu niet opnieuw checken hoe het add location veld werkt, want ik krijg melding van een internal server error. Later doe ik een nieuwe poging!

Hartelijke groet,

Lindsay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by LindsayJanssen** [comment]
Hee Martijn,

Ik heb net nogmaals geprobeerd om het dorp Gomshall (in Surrey, Engeland), toe te voegen. Ik krijg geen foutmelding, maar ook geen melding dat de plaats succesvol opgeslagen is. Als ik daarna onder 'view locations' kijk, staat Gomshall er niet; ook verschijnt het dorp niet als optie als ik een locatie probeer te selecteren onder 'add person'.

Hartelijke groet!

Lindsay

**Comment by martijnbentum** [comment]
hmm vreemd. Hoe voeg je de locatie toe? Vanuit een ander formulier en zo ja welke? Werkt het wel als je meteen add location kiest (vanuit het menu bovenaan)?

**Comment by LindsayJanssen** [comment]
Eerder probeerde ik het vanuit een ander formulier; vanochtend direct in ‘add location’. Ik heb het net nogmaals geprobeerd. Als ik op ‘save’  klik, wordt gewoon hetzelfde scherm weer geladen (de ingevulde info blijft wel behouden):

[cid:image002.png@01D6EF2A.753C2870]
Echter, ik kan dan de locatie niet vinden onder ‘view locations’  of wanneer ik in een ander formulier de plaats probeer op te halen. Ik heb ook geprobeerd de langere coordinaten van Google Maps toe te voegen, maar het effect bleef hetzelfde. Misschien doe ik iets doms met het toevoegen van coordinaten ofzo?

L.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by martijnbentum** [comment]
zou je de afbeelding kunnen uploaden op github, ik kan die niet zien.

Ik heb coordinaten met een komma en punt ingevoerd en beide werken

**Comment by martijnbentum** [comment]
lijkt nu opgelost
