### ISSUE TITLE
andere functie permission veld?

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#42]
Hee Martijn!

Kan het zijn dat het use permission veld nog aangepast moet worden, zodat je het kan gebruiken als filter zoals je eerder voorstelde? Als ik mij goed herinner, hadden we eerder afgesproken dat het veld 'permission' zou gaan heten, en dat er 3 opties in de drop-down zouden zijn: yes, no, request use permission. Jij zou dan die opties kunnen gebruiken om materialen te filteren, zodat materialen waarvoor we 'no' of 'request use permission' aangegeven hadden, niet zichtbaar zijn voor end users. Nu is dat laatste nog niet nodig totdat de repository beschikbaar wordt voor het publiek, maar het is wel handig om al die 2 opties voor het permission field te hebben.

Alvast hartelijk dank!

Lindsay

**Comment by martijnbentum** [comment]
Dat klopt. Ik ga ermee aan de slag

**Comment by martijnbentum** [comment]
Gedaan. Ik heb meteen ook het protocol aangepast.
Let wel op: De opties 'yes' en 'no' betekenen nu het omgekeerde van wat ze eerste betekende, dus als het al ingevuld was, moet dat waarschijnlijk aangepast worden. Als het nodig is kan ik opzoek gaan om welke entries het gaat.

**Comment by LindsayJanssen** [comment]
Bedankt Martijn! Is het veel moeite om te achterhalen om welke entries het gaat? Anders vraag ik de desbetreffende groepsleden wel even of ze zelf het veld permission bij hun entries opnieuw bekijken.

Hartelijke groet,

Lindsay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by LindsayJanssen** [comment]
Hee Martijn,

Ik ga er bij deze opmerking vanuit dat je het permission veld als filter kunt instellen (zodat alleen dat materiaal waar "yes" bij staat, zichtbaar/bruikbaar wordt voor de eindgebruiker). Het lijkt me slim de protocoltekst bij permission wat uit te breiden, zodat men snapt dat het veld als filter werkt: 

If you have permission to use the material, indicate "yes"; if you intend to request use permission, indicate "request use permission"; otherwise indicate "no". Only materials for which you indicated you have use permission will be made available to end users; other materials will remain invisible for end users.

**Comment by martijnbentum** [comment]
gedaan
