### ISSUE TITLE
protocol niet altijd zichtbaar

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#43]
Hee Martijn,

Ik weet niet of dit een tijdelijk probleem is, maar ik zie niet altijd een popup met protocoltekst als ik over een veld zweef met mijn cursus. Bijv., voor de meeste velden onder 'Add film' en bij 'Infographics' voor de velden vanaf 'collection' had ik dit probleem.

Alvast bedankt en hartelijke groet!

Lindsay

**Comment by martijnbentum** [comment]
Hoi Lindsay,

Ik heb net geprobeerd in Chrome en Safari en bij werkt het zonder problemen. Heb je het probleem nog steeds?

Groet,
Martijn

**Comment by LindsayJanssen** [comment]
Nee - nu zie ik gewoon alle pop ups weer. Raar dat dat even niet goed werkte, aangezien ik ook met Chrome werk.
