### ISSUE TITLE
keyword niet te selecteren?

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#44]
Hee Martijn!

Ik probeerde het keyword  "victims" te selecteren (was een van onze overkoepelende categorieën) maar kan het niet selecteren. Ik kan alleen het meer specifieke "victims\disease" selecteren. Weet jij hoe dit zit?

Hartelijke groet,

Lindsay

**Comment by martijnbentum** [comment]
Hoi Lindsay,

Ik denk dat het andersom is. Disease is de overkoepelende term (de overkoepelende term staat altijd achter de specifieke term.

Groet,
Martijn

<img width="394" alt="Screen Shot 2021-01-13 at 16 56 42" src="https://user-images.githubusercontent.com/19554953/104476475-8fd33f00-55c0-11eb-9bc4-bb1fe4eac7f2.png">
