### ISSUE TITLE
person pseudonym

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/heritages#45]
add a field that indicates whether a person entry is a pseudonym

suggested field name:
is pseudonym

suggested protocol text:
if this entry is for a pseudonym indicate yes, otherwise no

note:
if there are multiple authors and one or more authors has a pseudonym it will not be clear which author has the pseudonym

**Comment by martijnbentum** [comment]
Alternative solution:
add pseudonym field to person (multiple pseudonyms can be added)

make person name & pseudonym searchable when adding a person in another form

**Comment by martijnbentum** [comment]
Implemented the alternative solution.

**Comment by LindsayJanssen** [comment]
Your alternative solution sounds good!
