### ISSUE TITLE
icons voor file types

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#46]
Hee Martijn,

Ik heb wat icons uitgezocht op de website die je aanraadde:

- Voor tekst (ook boeken): https://fontawesome.com/icons/file-alt?style=solid
- Voor film: https://fontawesome.com/icons/video?style=solid 
- Voor muziek: https://fontawesome.com/icons/music?style=solid 
- Voor afbeeldingen (ook picture story): https://fontawesome.com/icons/image?style=solid 
- Voor infographics: https://fontawesome.com/icons/chart-area?style=solid

Het is het makkelijkst als ik deze keuzes zo aan jou doorgeef, zodat jij ermee aan de slag kan, toch? Of kunnen we dit beter anders aanpakken?

Hartelijke groet!

Lindsay

**Comment by martijnbentum** [comment]
Prima zo

**Comment by martijnbentum** [comment]
<i class="fas fa-file-alt"></i>	tekst / boeken
<i class="fas fa-video"></i> film
<i class="fas fa-music"></i> muziek
<i class="fas fa-image"></i> image /picture story
<i class="fas fa-chart-area"></i> infographics

<i class="fas fa-user"></i> person
<i class="fas fa-skull-crossbones"></i> famine
<i class="fas fa-exclamation"></i> famine

**Comment by LindsayJanssen** [comment]
Hoe hilarisch ik die skull & bones ook zou vinden, laten we inderdaad maar geen icoon uitzoeken voor famine.

Laten we voor person inderdaad die gebruiken die je voorstelt. Ik had origineel gedacht alleen iconen te gebruiken om de aard van materialen meteen visueel duidelijk te maken voor de eindgebruiker, maar dat kan ook geen kwaad voor personen.

Bedankt!

L.
