### ISSUE TITLE
Expliciete verwijzing naar copy in RU gedeelde werkgroepmap

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#47]
Hee Martijn,

Een vraag: we hadden afgesproken om alle files in de repository ook op de slaan in de gedeelde werkgroepmap op de U-schijf, in ieder geval totdat er een automatisch backup-systeem bestaat. Ik denk dat het goed is om dat ook expliciet te vermelden in de repository. Dat kunnen we op twee manier doen:

- ik voeg bij elke protocoltekst over het uploaden en benoemen van files toe: "Also make sure to save a copy of this file in the shared workgroup folder ("gedeelde werkgroepmap") on the University U-drive."
- jij voegt onderaan elk formulier dat ook de mogelijkheid geeft tot file uploads (dus famine en location bijv. niet), de volgende zin toe: "Also make sure to save a copy of the file you uploaded in the shared workgroup folder ("gedeelde werkgroepmap") on the University U-drive."

Wat is makkelijker, denk je?

**Comment by martijnbentum** [comment]
Beide lijken mij een goede optie, met als mogelijk probleem dat er overheen gelezen wordt

Ik heb inmiddels het backup systeem klaar, dus als het goed is worden de bestanden automatisch naar de werkgroepmap geschreven onder BACKUP/media/

Misschien kunnen jullie het ook testen of je het bestand ziet in de werkgroepmap als je het upload op de site?

**Comment by LindsayJanssen** [comment]
Als de backup werkt, worden beide opties overbodig lijkt me!

Ik heb het net geprobeerd met een test file, en het werkt in ieder geval voor tekst! De file (een pagina van een schoolboek in PDF format in dit geval) wordt bij opslaan meteen opgeslagen in de correcte subfolder van de BACKUP map. Wil je dat ik komende week het even test met elk type file? Ik laat de file entry in de repository en de file in de BACKUP map nog even staan, zodat jij het resultaat ook kunt zien – ik haal ze later weg.

Lindsay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
