### ISSUE TITLE
keyword "victims" toevoegen

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#48]
Hee Martijn,

Ik probeerde zelf het keyword "victim" toe te voegen, maar dan losgekoppeld van "disease" (omdat er ook mensen doodgaan aan andere dingen dan ziektes tijdens hongersnoden he). Dit lukt me echter niet, omdat de database dan terecht aangeeft dat het woord "victim" al bestaat. Hoe kan ik of jij victim toevoegen, los van "disease"? Als het aan een andere overkoepelende term gekoppeld moet worden, zou "people" de beste optie zijn.

Hartelijke groet!

Lindsay

**Comment by martijnbentum** [comment]
Ik kan victim aanpassen dat het onder People staat.
Wil je de mogelijkheid hebben keywords aan meerdere overkoepelende termen te koppelen?

Zoals het keyword toevoeg menu nu gemaakt is werkt het eigenlijk niet om nieuwe items toe te voegen als je die ook wilt kunnen koppelen aan overkoepelende termen. Als je verwacht dat er vaker veranderingen nodig zijn kan ik het aanpassen.

**Comment by LindsayJanssen** [comment]
Moeilijk om te zeggen, dan gaat pas echt duidelijk worden als meer groepsleden echt serieus aan de slag gaan met materialen toevoegen. Pas het voor de zekerheid maar aan, zodat ik termen kan koppelen aan meerdere overkoepelende termen. (Tenzij dat een hoop gedoe is natuurlijk!)

L.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by martijnbentum** [comment]
Ja is wel wat werk, geen probleem, maar wel goed om even duidelijk te hebben wat precies nodig is.

**Comment by LindsayJanssen** [comment]
Wellicht kunnen we het dan het beste even bespreken? Het aanpassen zou nu ook geen haast hebben hoor. Wellicht kunnen we het ook andersom doen, om je mogelijk werk te besparen: eerst gaat iedereen maar eens serieus aan de slag met entries, en dan kijken we of het nodig is.

Voor victims in ieder geval, maar dat is ook eigenlijk wel een duidelijk geval. Het is nu trouwens wel zo dat de twee keywords die ik heb toegevoegd dus niet onder een bredere categorie vallen; dat kan wellicht wat onoverzichtelijk worden.

Lindsay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by martijnbentum** [comment]
Ja bespreken is misschien wel even goed. Ik werk weer vanaf dinsdag en ben meestal wel bereikbaar.

Het kan wel handig zijn om dit snel goed te krijgen, omdat het iets is dat gelinkt wordt aan andere dingen en dan kan het lastig zijn als er later van alles veranderd moet worden.

victims zit nu onder people en niet meer onder disease

als je de twee keywords zonder overkoepelende categorie wilt verwijderen zou dat nu al moeten kunnen (door die te selecteren in de keywords lijst en op delete te klikken).

**Comment by LindsayJanssen** [comment]
Hee Martijn,

Sorry, ik kom er nu pas aan toe hiernaar te kijken. Als ik de keyword lijst bekijk (via add keyword) zie ik alleen een lijst van enkelvoudige keywords staan, niet aan welke overkoepelende categorie ze gelinkt zijn. Het is vanuit mijn perspectief dus lastig te zien of keywords bij een bepaalde categorie horen, en ik weet dat niet meer uit mijn hoofd voor alle woorden. Nu kan ik nog de enkele keywords die ik toegevoegd heb weghalen, maar als dat er meer worden, heb ik het overzicht daar dus niet op. Dat kan ik natuurlijk wel achterhalen door in een ander scherm keywords aan items toe te gaan voegen, maar dat is wel wat omslachtig.

Ik zal het dadelijk tijdens de meeting ook nog ter sprake brengen als we het over keywords hebben.

Hartelijke groet!

Lindsay
