### ISSUE TITLE
spelfoutje

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#50]
Hoi Martijn,

Bij het pseudonym veld staat "seperated" in plaats van "separated". Wat is makkelijker hierbij, en bij andere kleine foutjes die er mogelijk nog komen (ook door mijn typekunsten): dat ik de kleine aanpassing maak in de excel file en die vervolgens naar je mail, of direct doorgeef aan jou?

Bedankt!

Lindsay

**Comment by martijnbentum** [comment]
oeps
geef maar door
