### ISSUE TITLE
pseudonyms in view persons

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#51]
Hee Martijn,

Het nieuwe pseudonym veld werkt goed; bedankt! Ik had wel het volgende: bij wijze van proef had ik een fictief persoon ingevoerd met alleen een pseudonym, geen bekende eigen naam (een soort Banksy). Dit wordt goed opgeslagen, en ik kan later de entry ook terugvinden en verwijderen in logs. Echter, ik zie het pseudonym niet verschijnen in de view persons lijst? 

Hartelijke groet,

Lindsay

**Comment by martijnbentum** [comment]
Ik heb een pseudonyms kolom toegevoegd bij de persons lijst. Als ik een person toevoeg met alleen een pseudonym dan staat die in de lijst. Werkt het nu ook voor jou?

**Comment by LindsayJanssen** [comment]
Het werkt!
