### ISSUE TITLE
Change keyword interface to add keyword relations

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/heritages#52]
Keywords relations can now be changed by typemaster users.
To set or change category relations, the Category Keyword field  can be set. This field will only show category keywords.

For example, to set the economy category for agriculture, you can select the keyword economy in the Category Keyword field:

<img width="889" alt="Screen Shot 2021-02-19 at 09 49 53" src="https://user-images.githubusercontent.com/19554953/108480939-d9860800-7297-11eb-9910-25aa231a767e.png">

You can also view keywords in a list with associate category or related keywords:
<img width="853" alt="Screen Shot 2021-02-19 at 09 45 59" src="https://user-images.githubusercontent.com/19554953/108480476-4baa1d00-7297-11eb-883d-e9f8963619cf.png">

Note for keyword searching functionality:
searching for overarching keywords e.g. food finds all item with sub keywords e.g. bread
including overarching keyword to item will only be found with the overarching keyword term (not by searching for the keyword bread)

**Comment by LindsayJanssen** [comment]
Hee Martijn,

Zowel het "add" als het "view" scherm voor de keywords zijn super helder zo, en het toevoegen werkt fijn! Ik moest er wel even aan denken het vakje naast category aan te vinken (in plaats van alleen de categorie te selecteren uit het drop-down menu), dus als andere projectleden op termijn ook zelf keywords mogen gaan toevoegen, moeten we dat tegen die tijd vermelden in de protocoltekst.

Ter info: er zijn inmiddels enkele keywords die onder meerdere categorieën zouden kunnen vallen; zo kan "scarcity" zowel onder "food" (voedselschaarste) als "economy" (economische schaarste) vallen. Bij keywords waarbij ik het niet slim vind om ze slechts onder 1 categorie te laten vallen, heb ik geen categorie gekozen.

Hartelijke groet!

L.
