### ISSUE TITLE
creator field for film

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#57]
Hee Martijn,

Kun je bij 'Add Film' ook het veld 'Creator' toevoegen? Er worden wat news reports en amateur reports toegevoegd aan de repository, een daarvoor zijn de al bestaande velden 'Writers' en 'Directors' niet geschikt.

Bedankt!

Lindsay

**Comment by martijnbentum** [comment]
Ja zal ik doen.
Is dit ok voor de Protocol text:
Person who created this short movie e.g. news reports, amateur reports, etc.

**Comment by LindsayJanssen** [comment]
Bedankt! En zeker, die tekst is prima.

L.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
