### ISSUE TITLE
backup folder - inhoud map media-->media?

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#58]
Hee Martijn,

Ik bekeek net de backup folder in de gedeelde werkgroepmap, en daarbij viel me op dat een aantal bestanden die in de subfolder 'media' (onderdeel van de grotere folder 'media') staan, eigenlijk onder andere materiaaltypes vallen. Er staan bijv. een aantal thumbnails en images in, die eerder in de mappen 'thumbnail' en 'image' zouden moeten staan. Klopt dat, of zie ik dat verkeerd? Ik vermoed dat het files zijn die geüpload zijn voordat de automatische backup in werking werd gesteld. Moeten we die files even handmatig in de goede mappen zetten?

Verder lijkt het systeem goed te werken - heel fijn!

Hartelijke groet,

Lindsay

**Comment by martijnbentum** [comment]
Hoi Lindsay,

Ah fijn dat het goed werkt. Ja dat klopt de media folder is nog een overblijfsel van hoe het eerder was ingesteld. Ik dacht het zo maar te laten, om de kans te verkleinen dat een link tussen een entry en het bestand straks niet meer klopt.
Is dat ok?

Groet,
Martijn

**Comment by LindsayJanssen** [comment]
Ja hoor! Zo lang dat in een later stadium geen onduidelijkheid oplevert over die map en de inhoud.

Lindsay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
