### ISSUE TITLE
film release location

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/heritages#61]
release location: only mention most important locations preferably 1 location

add field:
released -> nationally, internationally

**Comment by martijnbentum** [comment]
Is an extra field necessary?
Target audience already indicates whether the film was released nationally or internationally

**Comment by LindsayJanssen** [comment]
Ja, laat maar zo. Blijkbaar weet ik soms ook niet meer wat ik allemaal in de protocols heb gezet. Kun je het zinnetje "Input locations of importance; not all locations have to be included" wel daarnaast ook toevoegen bij de protocol-tekst voor 'locations shot'? Dankje!

**Comment by martijnbentum** [comment]
gedaan
