### ISSUE TITLE
add field to person that sets whether pseudonym takes precedent

### ISSUE THREAD

**Issue by martijnbentum** [martijnbentum/heritages#65]

**Comment by martijnbentum** [comment]
Added a checkbox after the pseudonym field (and added instructions to the protocol). If the box is checked the pseudonym will be shown in the row information

**Comment by LindsayJanssen** [comment]
Goede aanpak! Ik zie alleen de toegevoegde protocol-instructies nog niet; niet bij het vakje, en ook niet bij 'pseudonym'?

**Comment by martijnbentum** [comment]
Zijn de instructies nu wel zichtbaar? (Bij mij wel althans)

**Comment by LindsayJanssen** [comment]
Ja, de tekst is nu zichtbaar!
