### ISSUE TITLE
Recorded speech type

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#66]
Hee Martijn,

Zoals beloofd het lijstje met velden dat gebruikt kan worden voor het Recorded speech:

- Title original
- Title English
- Recording type (News item, interview, information program, warning, request)
- Creators
- Speakers
- Broadcasting station,
- Date of recording
- Date of transmission
- Language(s) of recording,
- Location of recording
- Famines
- Keywords
- Collection
- Available
- Permission
- Description
- Comments

**Comment by martijnbentum** [comment]
Welke velden moeten dit object uniek maken?
title & date of recording?

**Comment by LindsayJanssen** [comment]
Title ben ik met je eens. Bij date of recording twijfel ik – ik ben zelf niet veel bezig geweest met dergelijke opnames, maar denk dat het makkelijker te achterhalen is wanneer iets uitgezonden is, dan wanneer het opgenomen is. Ik zou dus eerder voor date of transmission gaan.

L.

**Comment by martijnbentum** [comment]
uniek met de volgende velden: title & date of release

Ik heb recorded speech toegevoegd.
