### ISSUE TITLE
Memorial site lijstje

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#67]
Hee Martijn,

Wat raar - ik weet zeker dat ik dit gisteren als issue aangemaakt heb. Vast vergeten uiteindelijk te submitten ofzo. Opnieuw:

- Title original
- Title English
- Type of monument (sculpture, memorial plaque, statue, window)
- Artist/builder (deze is aangedragen door Ingrid en Helmi, maar ik vraag me af of de dubbele naam handig is. Wellicht 2 velden, Artist and Creator - voor het geval dat de artiest die het ontworpen heeft niet dezelfde persoon is als degene die het ontwerp uitvoert. Creator lijkt me daarnaast geschikter dan Builder)
-  Donors
- Location
- Date of construction
- Date of reveal
- Availibility
- Permission
- Keywords
- Famines
- Description 
- Comments
- De mogelijkheid een of meerdere afbeeldingen van het monument te uploaden 
- Videolink

Hartelijke groet!

Lindsay

**Comment by martijnbentum** [comment]
Is het mogelijk om een maximaal aantal foto's te bepalen, bijvoorbeeld zes?

**Comment by martijnbentum** [comment]
Ik heb memorial site toegevoegd.
Voor het toevoegen van meerdere afbeeldingen heb ik voor een simpele oplossing gekozen. Mocht dit niet werken dan hoor ik het graag.

**Comment by LindsayJanssen** [comment]
Dit lijkt me prima zo! Als ik vanuit de groep hoor dat mensen toch meer foto's willen toevoegen, laat ik het weten.
