### ISSUE TITLE
Memorial sites - insitutions or funding bodies toevoegen?

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#69]
Heet Martijn,

Kun je bij 'Donors'  in 'Memorial sites'  het mogelijk maken dat ook niet-personen toegevoegd kunnen worden? De protocol-tekst kan dan aangepast worden naar:

"Indicate which person(s), institution(s) or funding bodies financially contributed to the memorial site."

Hartelijk dank!

L

**Comment by martijnbentum** [comment]
Het huidige veld linkt naar Person. Dit veld accepteert alleen personen. Ik zou een extra veld kunnen maken met een link naar Institution.

veld namen:
Donor (person)
Donor (institution)
