### ISSUE TITLE
kleine aanpassing tekst protocol Recorded Speech

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#70]
Hee Martijn,

Veel dank voor het invullen voor de protocollen bij de nieuwe materiaaltypes! Ik heb een paar kleine aanpassing bij 'Recorded Speech' --> 'languages': daar staat nu het woord 'game', dat moet ' recorded speech' zijn.

Excuses dat ik dit niet via de Excelsheet doe - ik heb even wat gehannes met Excel.

Lindsay

**Comment by martijnbentum** [comment]
gedaan
