### ISSUE TITLE
Wat kleine aanpassingen voor de protocolteksten bij Memorial sites

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#73]
Hee Martijn,

Hier zijn wat kleine aanpassingen voor in de protocolteksten bij Memorial sites. Ze zijn zo klein dat het me makkelijk leek de aanpassingen zo door te geven, dan aan te passen in de Excel. Krijg jij sowieso melding van aanpassingen door mij gedaan in de Excel? Niet dat ik dat recentelijk heb gedaan, maar dan weet ik dat voor in de toekomst.

Ik gebruik [ ] om een toevoeging aan te duiden:
- Commissioning persons: verander de zin "If the person, is not yet included, add them using the plus sign next to the 'commissioning field' --> "If the person is not yet included, add that person using the plus sign next to the 'commissioning persons' field."
- Commissioning institutions: verander "them" naar "it" in de zin "If the institution, or funding body is not yet included, add THEM using..."
- Setting: "Select the location [the] memorial site is about"

Wederom veel dank! L.

**Comment by martijnbentum** [comment]
gedaan
