### ISSUE TITLE
Settingstekst in protocol aanpassen.

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#76]
Hee Martijn,

Het volgende moet toegevoegd worden aan de protocolteksten voor alle setting velden: 

"If the setting is unknown, please indicate a broader geographical region, such as country. To avoid cluttering the map, mention one location here; only list two or a few locations if these are of equal importance for the material. You can also mention secondary locations in your description."

Is het makkelijker als ik dit aanpas in de Excel of als jij dit C+P? Als het eerste makkelijker is, zeg dat dan vooral; dan pas ik dat vandaag of morgen even aan.

Bedankt!

Lindsay

**Comment by martijnbentum** [comment]
Ik heb de volgende tekst toegevoegd:
Try to always enter a location here. If the setting is unknown, please indicate a broader geographical region, such as country. To avoid cluttering the map, mention one location here; only list two or a few locations if these are of equal importance for the material. You can also mention secondary locations in your description.
