### ISSUE TITLE
zoekopdrachten verfijnen

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#77]
Hee Martijn,

N.a.v. onze bespreking is dit het lijstje geworden voor het verder verfijnen van zoekopdrachten:

- tijdsindicatie: met slider of het invoeren van begin- en einddata
- types of material, met verdere specificatie naar subtypes (dus niet alleen tekst, maar ook verder kunnen specificeren naar novels, poems, articles, etc.).
- location(s)
- famine(s)
- keywords: sowieso de overkoepelende categorie-woorden; indien haalbaar ook alle keywords.

De meer specifieke elementen hierboven  (subtypes en alle keywords) zijn misschien afhankelijk van de vraag die je (terecht) stelde: hoeveel moeite hierin te steken, niet wetende of de beoogde eindgebruiker ook daadwerkelijk gebruik maakt (en kan blijven maken) van de repository, dus ik kan me voorstellen dat je even wacht met dat finetunen totdat er meer duidelijkheid is over het toekomstig gebruik van de repository.

Bedankt en hartelijk groet!

L.

**Comment by martijnbentum** [comment]
moved to issue 108
