### ISSUE TITLE
kwaliteit thumbnails -> protocol

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#83]
Hee Martijn,

De kwaliteit van sommige thumbnails is behoorlijk slecht. Misschien moeten we een minimumstandaard instellen; wat denk jij? En is het ook mogelijk om te zorgen dat afbeeldingen van te slechte kwaliteit niet geüpload kunnen worden, of zou dat teveel gedoe zijn? Als dat laatste het geval is, kan ik wellicht ook in de protocol zetten wat de minimumkwaliteit van een afbeelding moet zijn.

Bedankt!

**Comment by martijnbentum** [comment]
Het is niet triviaal om de kwaliteit van een afbeelding automatisch te bepalen. Ik denk dat het beter in het protocol opgelost kan worden.

**Comment by LindsayJanssen** [comment]
Dat ben ik met je eens, maar ik vraag me tegelijkertijd ook af elke betrokkene dat dan ook kan/gaat doen. Misschien is de beste oplossing dan dat we een minimum kwaliteit (wellicht minimum PPI) stellen in het protocol, en ook vragen of ieder zijn/haar afbeeldingen checkt op kwaliteit na uploaden? Dus dan zoiets: "Please make sure to upload an image with a minimum of XX pixels per inch [pixel dichtheid] and which does not exceed 400X400 pixels (or about 300kb). After uploading your image, look at it, to see whether it is of sufficient quality." Ik voeg dat in blokhaken toe, om zeker te weten dat iedereen snapt wat bedoeld wordt.

**Comment by martijnbentum** [comment]
Ik heb het volgende toegevoegd (om het een beetje kort te houden):
After uploading your image, look at it, to see whether it is of sufficient quality.
