### ISSUE TITLE
tweede niveau view tile view

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#84]
Hee Martijn,

Doordat de tiles nu alleen een afbeelding plus titel bevatten is het vrij onduidelijk waar ze precies betrekking op hebben. Per materiaal zijn andere velden relevant om in te voegen, dus wellicht is de meest consistente oplossing door overal bij aanklikken de description te laten zien? Hier is ruimte voldoende voor bij de preview en dan heeft de eindgebruiker direct alle relevante informatie.

Bedankt!

**Comment by martijnbentum** [comment]
Hmm. Het leek mij goed om de tile view vooral over de afbeeldingen te laten gaan. Veel tekst kan dan voor afleiding zorgen. 

Het tweede niveau bevat afbeelding, titel en datum en je kan op de titel klikken om verdere informatie te krijgen (is nu nog edit view, maar wordt uiteindelijk de 'full' view pagina). Ik had nu nog geen icon bij het tweede niveau, maar kan die nog toevoegen voor extra duiding.

Ik kan description toevoegen als je denkt dat het toch beter is.

**Comment by LindsayJanssen** [comment]
Ik snap je punt hier - is het veel moeite om uit te proberen hoe het eruit ziet met description in het tweede niveau of met een icon op het tweede niveau? 

Voor context: we hebben nu niet met de hele projectgroep kunnen vergaderen. Leden hebben mij hun punten gemaild en ik heb ze met jou gedeeld. Het is dus niet zo dat dit een punt is van de hele groep. Als het niet teveel moeite is (zo wel, dan kun je ook alleen de opties beschrijven, geen probleem), kunnen we ook de verschillende opties met de hele groep bespreken in de volgende vergadering en dan kiezen wat ons het beste lijkt.
