### ISSUE TITLE
Personen en famines? En dan famines ook zichtbaar in de preview lijst

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#85]
Hee Martijn,

Sorry, dit zijn twee handelingen in 1 issue, maar als ik ze los post, is het misschien onduidelijk:
1. Kunnen we bij 'Add person' ook hongersnoden invoegen? 
2. Kunnen we in de list view bij personen dan ook de famine(s) laten zien in de preview?

Bedankt!

**Comment by martijnbentum** [comment]
gedaan
