### ISSUE TITLE
maximum aantal tekens

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#86]
Hee Martijn,

De descriptions lijken bij sommige materialen een stuk langer dan 500 tekens; dit leidt tot inconsistentie in de list view. Is het mogelijk om een automatische begrenzing op het description veld te zetten, zodat niemand over de 500 tekens kan gaan?

Bedankt!

**Comment by martijnbentum** [comment]
Het is zeker mogelijk, maar volgens mij was het idee dat dit alleen het protocol stond zodat de description langer kon zijn als het echt nodig was?

In de list view zie je de description alleen helemaal bij het tweede niveau, dus dan is er toch consistentie probleem?

Moeten alle huidige descriptions afgekapt worden op 500 tekens?

**Comment by LindsayJanssen** [comment]
Hmmm, daar heb je een punt. Ik had gehoopt dat onze groepsleden zich wat beter aan de 500 tekens zouden houden (misschien ben ik zelf ook wel schuldig aan overschrijding hier!). Het lijkt me niet wenselijk om wat al ingevoerd is, zomaar af te kappen, want dan missen we een stuk tekst. Misschien kunnen we een teller in het invoerveld zetten, die rood wordt zodra je over de 500 heen gaat?

De inconsistentie is inderdaad alleen op het tweede niveau. Is dit een idee: om hier gewoon nooit meer dan 500 woorden te laten zien, ongeacht of de volledige description langer is?

(En ik denk dat we, nu we wat meer met dit veld gewerkt hebben, eens moeten polsen wat iedereen vindt van de 500 tekens - eentje voor op de lijst me bespreekpunten.)

**Comment by martijnbentum** [comment]
Misschien kunnen we een teller in het invoerveld zetten, die rood wordt zodra je over de 500 heen gaat?

Gedaan
