### ISSUE TITLE
new category material artefact

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#95]
Added a new category Material Artefact with the following fields (see below)

The entries should be unique based on the following three fields

'title_original','date_created','image_filename'

Fields:
title original
title english
artefact type
creators
source link
image file
locations
setting
date created
famines
keywords
collection
available
permission
rated
description
comments
thumbnail

-------

Hee Martijn,

Tijdens de vergadering hadden we besloten materials artefacts onder te brengen onder images, en dan keywords ervoor toe te voegen. (Zie mijn toevoegingen onder de overkoepelende term 'material artefact' in de keyword lijst.) Ik heb geen aparte image type hiervoor aangemaakt (want het blijft een photograph, niet?).

Als ik me niet vergis, hebben we toen ook besloten dat het geen goed idee is om de maker van de foto van het object (bijvoorbeeld ikzelf als ik een foto maak van een oud gebruiksvoorwerp) op te nemen als creator, want dat schept verwarring. Die info moet in de protocoltekst, zonder dat de tekst te lang of diffuus wordt. Wat vind je van de volgende toevoeging (als zin achter de bestaande protocoltekst)?

"The person who made the photograph of a material artefact or object (so not the official artist) should not be listed here."

Ik probeer het zo kort mogelijk te houden, en hoop dat dit zo duidelijk genoeg is.

L.

**Comment by martijnbentum** [comment]
Volgens mij is het ook geen goed idee om de maker van het object in dit veld te noemen en nu lijkt het erop alsof de tekst dat wel aanraadt. In de descriptie zou misschien de naam van de maker van het object kunnen komen.

"If the photograph is mostly object an object, do not list the creator of the object or the photographer here. You could mention the object creator in the description if relevant. "

**Comment by LindsayJanssen** [comment]
This looks good! I'll update the protocol later this week.
