### ISSUE TITLE
Always fill in setting (protocol)

### ISSUE THREAD

**Issue by LindsayJanssen** [martijnbentum/heritages#96]
Hee Martijn,

Ik moet in de protocollen bij alle setting fields aangeven dat men die fields altijd moet invullen als het kan, omdat setting location getoond wordt in tile/list view. Wat vind je handiger: dat ik alle beschrijvingen even naloop in de protocol Excel, ze aanpas, en je een seintje geef als ik dat gedaan heb, of dat ik je via een GitHub issue een zin geef om toe te voegen bij alle setting fields? Laat maar weten wat je voorkeur heeft!

L.

**Comment by martijnbentum** [comment]
Hoi Lindsay,
Sorry voor de late reactie. Ik moest wat technische dingen oplossen. Ik denk dat het toch een goed idee is om de protocol popups aanpasbaar te maken, omdat de protocols toch regelmatig veranderen. Ik wil dat volgende week doen, is dat ok?
Groet,Martijn

**Comment by martijnbentum** [comment]
Ik heb de volgende tekst toegevoegd:
Try to always enter a location here. If the setting is unknown, please indicate a broader geographical region, such as country. To avoid cluttering the map, mention one location here; only list two or a few locations if these are of equal importance for the material. You can also mention secondary locations in your description.
